-- V22: Add reminder tracking to dispatches
ALTER TABLE DISPATCHES ADD LAST_REMINDER_AT TIMESTAMP;
ALTER TABLE DISPATCHES ADD MAX_REMINDERS NUMBER DEFAULT 3;
ALTER TABLE DISPATCHES ADD REMINDER_INTERVAL_DAYS NUMBER DEFAULT 3;

CREATE INDEX idx_dispatches_reminder ON DISPATCHES(DISPATCH_STATUS, LAST_REMINDER_AT);
