-- V23: Add pulse survey automation fields
ALTER TABLE SURVEYS ADD FREQUENCY VARCHAR2(20);
ALTER TABLE SURVEYS ADD NEXT_SCHEDULED_AT TIMESTAMP;
ALTER TABLE SURVEYS ADD PARENT_SURVEY_ID NUMBER;

CREATE INDEX idx_surveys_frequency ON SURVEYS(FREQUENCY);
CREATE INDEX idx_surveys_next_scheduled ON SURVEYS(NEXT_SCHEDULED_AT);
